### ISSUE TITLE
Display locations on a map

### ISSUE THREAD

**Issue by andreas-bauer** [sensor-network/open-data-portal#47]
Displaying lat & long coordinates for the location of a meassurement is not human readable. 
Even with city names it is not always clear how close the city is (for non locals).
Therefore, please provide a way to represent the location on a map.

I suggest one of the following options:
a) Make locations clickable so that a new tab with Open Street Map (OSM) or Google Maps opens.
b) Integrate a OSM or Google Maps frame into the view. I guess OSM would be better since Google Maps needs API keys that then needs to be managed.

**Comment by juliusmarminge** [comment]
@andreas-bauer This is a feature we have had in our backlog since the start. React has a very good integration with Google Maps but as you said it requires an API key which we were worried was not viable for this project. After some quick googling I found this library called [Leaflet](https://react-leaflet.js.org). What do you think about that, or should we just embed an iframe?

**Comment by andreas-bauer** [comment]
Leaflet seems to be a good choice for OSM integration. 👍
